export const STARTOVER = 'STARTOVER';
export const SET_WELL = 'SET_WELL';
export const SET_DISCIPLINE = 'SET_DISCIPLINE';
export const SET_CURR_TOPIC = 'SET_CURR_TOPIC';
export const SET_TOPICS_REQUIRED = 'SET_TOPICS_REQUIRED';
export const SET_TOPICS_OPTIONAL = 'SET_TOPICS_OPTIONAL';
